islandora_gsearcher.settings:
  type: config_object
  label: Settings
  mapping:
    islandora_gsearcher_gsearch_url:
      type: string
    islandora_gsearcher_gsearch_user:
      type: string
    islandora_gsearcher_gsearch_pass:
      type: string
